/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'admin' : null };
export type Timestamp = bigint;
export interface Tournament {
  'id' : bigint,
  'status' : TournamentStatus,
  'title' : string,
  'venue' : string,
  'startsAt' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'capacity' : bigint,
  'format' : TournamentFormat,
}
export type TournamentFormat = { 'doubles' : null } |
  { 'singles' : null };
export interface TournamentInput {
  'status' : TournamentStatus,
  'title' : string,
  'venue' : string,
  'startsAt' : Timestamp,
  'description' : string,
  'capacity' : bigint,
  'format' : TournamentFormat,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface User {
  'id' : UserId,
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : [] | [Role],
  'avatar' : [] | [ExternalBlob],
}
export type UserId = Principal;
export interface UserInput {
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserRoleView {
  'id' : UserId,
  'username' : string,
  'displayName' : string,
  'role' : [] | [Role],
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapOwner' : ActorMethod<[], undefined>,
  'createTournament' : ActorMethod<[TournamentInput], Tournament>,
  'createUser' : ActorMethod<[UserId, UserInput], User>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserByUsername' : ActorMethod<[string], [] | [User]>,
  'grantAdminRole' : ActorMethod<[UserId], UserRoleView>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'listUsersWithRoles' : ActorMethod<[], Array<UserRoleView>>,
  'revokeAdminRole' : ActorMethod<[UserId], UserRoleView>,
  'schema' : ActorMethod<[], string>,
  'updateTournament' : ActorMethod<[bigint, TournamentInput], Tournament>,
  'updateUser' : ActorMethod<[UserId, UserInput], User>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];