/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const TournamentSlot = IDL.Variant({ 'a' : IDL.Null, 'b' : IDL.Null });
export const TournamentElimination = IDL.Variant({
  'singleElimination' : IDL.Null,
  'doubleElimination' : IDL.Null,
});
export const TournamentCommand = IDL.Variant({
  'prioritizeMatch' : IDL.Nat,
  'startMatch' : IDL.Nat,
  'setMatchPlayers' : IDL.Record({
    'matchId' : IDL.Nat,
    'playerA' : IDL.Opt(IDL.Nat),
    'playerB' : IDL.Opt(IDL.Nat),
  }),
  'undo' : IDL.Null,
  'placePlayer' : IDL.Record({
    'playerId' : IDL.Nat,
    'slot' : TournamentSlot,
    'matchId' : IDL.Nat,
  }),
  'prioritizePlayer' : IDL.Nat,
  'generateBracket' : IDL.Null,
  'movePlayer' : IDL.Record({
    'playerId' : IDL.Nat,
    'slot' : TournamentSlot,
    'matchId' : IDL.Nat,
  }),
  'swapPlayers' : IDL.Record({
    'firstSlot' : TournamentSlot,
    'secondSlot' : TournamentSlot,
    'firstMatchId' : IDL.Nat,
    'secondMatchId' : IDL.Nat,
  }),
  'removePlayer' : IDL.Record({ 'playerId' : IDL.Nat, 'confirmed' : IDL.Bool }),
  'configure' : IDL.Record({
    'elimination' : TournamentElimination,
    'tableCount' : IDL.Nat,
  }),
  'assignTable' : IDL.Record({
    'table' : IDL.Opt(IDL.Nat),
    'matchId' : IDL.Nat,
  }),
  'assignBye' : IDL.Record({ 'slot' : TournamentSlot, 'matchId' : IDL.Nat }),
  'recordResult' : IDL.Record({
    'scoreA' : IDL.Nat,
    'scoreB' : IDL.Nat,
    'matchId' : IDL.Nat,
  }),
  'resetMatch' : IDL.Record({ 'cascade' : IDL.Bool, 'matchId' : IDL.Nat }),
  'addPlayer' : IDL.Record({ 'name' : IDL.Text, 'skillLevel' : IDL.Nat }),
  'editPlayer' : IDL.Record({
    'playerId' : IDL.Nat,
    'name' : IDL.Text,
    'skillLevel' : IDL.Nat,
  }),
});
export const Timestamp = IDL.Int;
export const TournamentAction = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'caption' : IDL.Text,
});
export const TournamentTableStatus = IDL.Variant({
  'available' : IDL.Null,
  'playing' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
});
export const TournamentTable = IDL.Record({
  'status' : TournamentTableStatus,
  'matchId' : IDL.Opt(IDL.Nat),
  'number' : IDL.Nat,
});
export const TournamentMatchStatus = IDL.Variant({
  'bye' : IDL.Null,
  'cancelled' : IDL.Null,
  'blocked' : IDL.Null,
  'completed' : IDL.Null,
  'playing' : IDL.Null,
  'ready' : IDL.Null,
});
export const TournamentBracket = IDL.Variant({
  'losers' : IDL.Null,
  'grandFinal' : IDL.Null,
  'resetFinal' : IDL.Null,
  'winners' : IDL.Null,
});
export const MatchSource = IDL.Variant({
  'bye' : IDL.Null,
  'player' : IDL.Nat,
  'winner' : IDL.Nat,
  'loser' : IDL.Nat,
});
export const TournamentMatch = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentMatchStatus,
  'table' : IDL.Opt(IDL.Nat),
  'winnerId' : IDL.Opt(IDL.Nat),
  'scoreA' : IDL.Opt(IDL.Nat),
  'scoreB' : IDL.Opt(IDL.Nat),
  'loserId' : IDL.Opt(IDL.Nat),
  'manualOverride' : IDL.Bool,
  'playerA' : IDL.Opt(IDL.Nat),
  'playerB' : IDL.Opt(IDL.Nat),
  'bracket' : TournamentBracket,
  'sourceA' : MatchSource,
  'sourceB' : MatchSource,
  'priority' : IDL.Int,
  'position' : IDL.Nat,
  'round' : IDL.Nat,
});
export const TournamentPlayerStatus = IDL.Variant({
  'advanced' : IDL.Null,
  'playing' : IDL.Null,
  'eliminated' : IDL.Null,
  'champion' : IDL.Null,
  'waiting' : IDL.Null,
  'ready' : IDL.Null,
  'removed' : IDL.Null,
});
export const TournamentPlayer = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentPlayerStatus,
  'table' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'seed' : IDL.Opt(IDL.Nat),
  'losses' : IDL.Nat,
  'registrationNumber' : IDL.Nat,
  'currentMatchId' : IDL.Opt(IDL.Nat),
  'skillLevel' : IDL.Nat,
  'registeredAt' : Timestamp,
});
export const TournamentState = IDL.Record({
  'elimination' : TournamentElimination,
  'started' : IDL.Bool,
  'waitingQueue' : IDL.Vec(IDL.Nat),
  'nextMatches' : IDL.Vec(IDL.Nat),
  'history' : IDL.Vec(TournamentAction),
  'canUndo' : IDL.Bool,
  'tables' : IDL.Vec(TournamentTable),
  'updatedAt' : Timestamp,
  'matches' : IDL.Vec(TournamentMatch),
  'players' : IDL.Vec(TournamentPlayer),
  'tableCount' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'championId' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const TournamentFormat = IDL.Variant({
  'doubles' : IDL.Null,
  'singles' : IDL.Null,
});
export const TournamentInput = IDL.Record({
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'startsAt' : Timestamp,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
  'format' : TournamentFormat,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'startsAt' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'capacity' : IDL.Nat,
  'format' : TournamentFormat,
});
export const UserId = IDL.Principal;
export const UserInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Opt(Role),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserRoleView = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : IDL.Opt(Role),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'applyTournamentCommand' : IDL.Func(
      [IDL.Nat, TournamentCommand],
      [TournamentState],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapOwner' : IDL.Func([], [], []),
  'createTournament' : IDL.Func([TournamentInput], [Tournament], []),
  'createUser' : IDL.Func([UserId, UserInput], [User], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentState' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TournamentState)],
      ['query'],
    ),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'grantAdminRole' : IDL.Func([UserId], [UserRoleView], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listUsersWithRoles' : IDL.Func([], [IDL.Vec(UserRoleView)], ['query']),
  'revokeAdminRole' : IDL.Func([UserId], [UserRoleView], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateTournament' : IDL.Func([IDL.Nat, TournamentInput], [Tournament], []),
  'updateUser' : IDL.Func([UserId, UserInput], [User], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const TournamentSlot = IDL.Variant({ 'a' : IDL.Null, 'b' : IDL.Null });
  const TournamentElimination = IDL.Variant({
    'singleElimination' : IDL.Null,
    'doubleElimination' : IDL.Null,
  });
  const TournamentCommand = IDL.Variant({
    'prioritizeMatch' : IDL.Nat,
    'startMatch' : IDL.Nat,
    'setMatchPlayers' : IDL.Record({
      'matchId' : IDL.Nat,
      'playerA' : IDL.Opt(IDL.Nat),
      'playerB' : IDL.Opt(IDL.Nat),
    }),
    'undo' : IDL.Null,
    'placePlayer' : IDL.Record({
      'playerId' : IDL.Nat,
      'slot' : TournamentSlot,
      'matchId' : IDL.Nat,
    }),
    'prioritizePlayer' : IDL.Nat,
    'generateBracket' : IDL.Null,
    'movePlayer' : IDL.Record({
      'playerId' : IDL.Nat,
      'slot' : TournamentSlot,
      'matchId' : IDL.Nat,
    }),
    'swapPlayers' : IDL.Record({
      'firstSlot' : TournamentSlot,
      'secondSlot' : TournamentSlot,
      'firstMatchId' : IDL.Nat,
      'secondMatchId' : IDL.Nat,
    }),
    'removePlayer' : IDL.Record({
      'playerId' : IDL.Nat,
      'confirmed' : IDL.Bool,
    }),
    'configure' : IDL.Record({
      'elimination' : TournamentElimination,
      'tableCount' : IDL.Nat,
    }),
    'assignTable' : IDL.Record({
      'table' : IDL.Opt(IDL.Nat),
      'matchId' : IDL.Nat,
    }),
    'assignBye' : IDL.Record({ 'slot' : TournamentSlot, 'matchId' : IDL.Nat }),
    'recordResult' : IDL.Record({
      'scoreA' : IDL.Nat,
      'scoreB' : IDL.Nat,
      'matchId' : IDL.Nat,
    }),
    'resetMatch' : IDL.Record({ 'cascade' : IDL.Bool, 'matchId' : IDL.Nat }),
    'addPlayer' : IDL.Record({ 'name' : IDL.Text, 'skillLevel' : IDL.Nat }),
    'editPlayer' : IDL.Record({
      'playerId' : IDL.Nat,
      'name' : IDL.Text,
      'skillLevel' : IDL.Nat,
    }),
  });
  const Timestamp = IDL.Int;
  const TournamentAction = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'caption' : IDL.Text,
  });
  const TournamentTableStatus = IDL.Variant({
    'available' : IDL.Null,
    'playing' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const TournamentTable = IDL.Record({
    'status' : TournamentTableStatus,
    'matchId' : IDL.Opt(IDL.Nat),
    'number' : IDL.Nat,
  });
  const TournamentMatchStatus = IDL.Variant({
    'bye' : IDL.Null,
    'cancelled' : IDL.Null,
    'blocked' : IDL.Null,
    'completed' : IDL.Null,
    'playing' : IDL.Null,
    'ready' : IDL.Null,
  });
  const TournamentBracket = IDL.Variant({
    'losers' : IDL.Null,
    'grandFinal' : IDL.Null,
    'resetFinal' : IDL.Null,
    'winners' : IDL.Null,
  });
  const MatchSource = IDL.Variant({
    'bye' : IDL.Null,
    'player' : IDL.Nat,
    'winner' : IDL.Nat,
    'loser' : IDL.Nat,
  });
  const TournamentMatch = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentMatchStatus,
    'table' : IDL.Opt(IDL.Nat),
    'winnerId' : IDL.Opt(IDL.Nat),
    'scoreA' : IDL.Opt(IDL.Nat),
    'scoreB' : IDL.Opt(IDL.Nat),
    'loserId' : IDL.Opt(IDL.Nat),
    'manualOverride' : IDL.Bool,
    'playerA' : IDL.Opt(IDL.Nat),
    'playerB' : IDL.Opt(IDL.Nat),
    'bracket' : TournamentBracket,
    'sourceA' : MatchSource,
    'sourceB' : MatchSource,
    'priority' : IDL.Int,
    'position' : IDL.Nat,
    'round' : IDL.Nat,
  });
  const TournamentPlayerStatus = IDL.Variant({
    'advanced' : IDL.Null,
    'playing' : IDL.Null,
    'eliminated' : IDL.Null,
    'champion' : IDL.Null,
    'waiting' : IDL.Null,
    'ready' : IDL.Null,
    'removed' : IDL.Null,
  });
  const TournamentPlayer = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentPlayerStatus,
    'table' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'seed' : IDL.Opt(IDL.Nat),
    'losses' : IDL.Nat,
    'registrationNumber' : IDL.Nat,
    'currentMatchId' : IDL.Opt(IDL.Nat),
    'skillLevel' : IDL.Nat,
    'registeredAt' : Timestamp,
  });
  const TournamentState = IDL.Record({
    'elimination' : TournamentElimination,
    'started' : IDL.Bool,
    'waitingQueue' : IDL.Vec(IDL.Nat),
    'nextMatches' : IDL.Vec(IDL.Nat),
    'history' : IDL.Vec(TournamentAction),
    'canUndo' : IDL.Bool,
    'tables' : IDL.Vec(TournamentTable),
    'updatedAt' : Timestamp,
    'matches' : IDL.Vec(TournamentMatch),
    'players' : IDL.Vec(TournamentPlayer),
    'tableCount' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'championId' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TournamentFormat = IDL.Variant({
    'doubles' : IDL.Null,
    'singles' : IDL.Null,
  });
  const TournamentInput = IDL.Record({
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'startsAt' : Timestamp,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
    'format' : TournamentFormat,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'startsAt' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'capacity' : IDL.Nat,
    'format' : TournamentFormat,
  });
  const UserId = IDL.Principal;
  const UserInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Opt(Role),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserRoleView = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : IDL.Opt(Role),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'applyTournamentCommand' : IDL.Func(
        [IDL.Nat, TournamentCommand],
        [TournamentState],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapOwner' : IDL.Func([], [], []),
    'createTournament' : IDL.Func([TournamentInput], [Tournament], []),
    'createUser' : IDL.Func([UserId, UserInput], [User], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentState' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TournamentState)],
        ['query'],
      ),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'grantAdminRole' : IDL.Func([UserId], [UserRoleView], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listUsersWithRoles' : IDL.Func([], [IDL.Vec(UserRoleView)], ['query']),
    'revokeAdminRole' : IDL.Func([UserId], [UserRoleView], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateTournament' : IDL.Func([IDL.Nat, TournamentInput], [Tournament], []),
    'updateUser' : IDL.Func([UserId, UserInput], [User], []),
  });
};

export const init = ({ IDL }) => { return []; };